# Site settings
title: "May+Helder"
description: |
    Dipolog City, Philippines

    March 28, 2019
owner: May and Hélder
first_published: 2017
email: helder@helmo.ai
baseurl: "" # the subpath of your site, e.g. /blog
url: "www.mayandhelder.com" # the base hostname & protocol for your site

social:
  instagram: https://instagram.com/mayandhelder/

# Build settings
markdown: kramdown
