# Site settings
title: "May + Helder"
description: |
    Dipolog City, Philippines

    March 28, 2019
owner: Mark Cerqueira
first_published: 2017
email: helder@helmo.ai
baseurl: "" # the subpath of your site, e.g. /blog
url: "www.mayandhelder.com" # the base hostname & protocol for your site

social:
  github: https://github.com/markcerqueira/wedding-site

# Build settings
markdown: kramdown
